# -*- coding: utf-8 -*-
"""
語彙データベース
level: 1=日常単語, 2=日常会話, 3=学校生活, 4=日本での生活, 5=上級表現
"""

VOCAB_DATA = [
    # ---------------- Level 1: 日常単語 ----------------
    {"id": "L1-01", "level": 1, "japanese": "水", "reading": "みず", "vietnamese": "Nước"},
    {"id": "L1-02", "level": 1, "japanese": "火", "reading": "ひ", "vietnamese": "Lửa"},
    {"id": "L1-03", "level": 1, "japanese": "食べる", "reading": "たべる", "vietnamese": "Ăn"},
    {"id": "L1-04", "level": 1, "japanese": "飲む", "reading": "のむ", "vietnamese": "Uống"},
    {"id": "L1-05", "level": 1, "japanese": "学校", "reading": "がっこう", "vietnamese": "Trường học"},
    {"id": "L1-06", "level": 1, "japanese": "家", "reading": "いえ", "vietnamese": "Nhà"},
    {"id": "L1-07", "level": 1, "japanese": "車", "reading": "くるま", "vietnamese": "Xe hơi"},
    {"id": "L1-08", "level": 1, "japanese": "本", "reading": "ほん", "vietnamese": "Sách"},
    {"id": "L1-09", "level": 1, "japanese": "友達", "reading": "ともだち", "vietnamese": "Bạn bè"},
    {"id": "L1-10", "level": 1, "japanese": "先生", "reading": "せんせい", "vietnamese": "Giáo viên"},
    {"id": "L1-11", "level": 1, "japanese": "犬", "reading": "いぬ", "vietnamese": "Chó"},
    {"id": "L1-12", "level": 1, "japanese": "猫", "reading": "ねこ", "vietnamese": "Mèo"},
    {"id": "L1-13", "level": 1, "japanese": "魚", "reading": "さかな", "vietnamese": "Cá"},
    {"id": "L1-14", "level": 1, "japanese": "鳥", "reading": "とり", "vietnamese": "Chim"},
    {"id": "L1-15", "level": 1, "japanese": "花", "reading": "はな", "vietnamese": "Hoa"},
    {"id": "L1-16", "level": 1, "japanese": "木", "reading": "き", "vietnamese": "Cây"},
    {"id": "L1-17", "level": 1, "japanese": "空", "reading": "そら", "vietnamese": "Bầu trời"},
    {"id": "L1-18", "level": 1, "japanese": "海", "reading": "うみ", "vietnamese": "Biển"},
    {"id": "L1-19", "level": 1, "japanese": "山", "reading": "やま", "vietnamese": "Núi"},
    {"id": "L1-20", "level": 1, "japanese": "川", "reading": "かわ", "vietnamese": "Sông"},
    {"id": "L1-21", "level": 1, "japanese": "雨", "reading": "あめ", "vietnamese": "Mưa"},
    {"id": "L1-22", "level": 1, "japanese": "雪", "reading": "ゆき", "vietnamese": "Tuyết"},
    {"id": "L1-23", "level": 1, "japanese": "風", "reading": "かぜ", "vietnamese": "Gió"},
    {"id": "L1-24", "level": 1, "japanese": "朝", "reading": "あさ", "vietnamese": "Buổi sáng"},
    {"id": "L1-25", "level": 1, "japanese": "昼", "reading": "ひる", "vietnamese": "Buổi trưa"},
    {"id": "L1-26", "level": 1, "japanese": "夜", "reading": "よる", "vietnamese": "Buổi tối"},
    {"id": "L1-27", "level": 1, "japanese": "今日", "reading": "きょう", "vietnamese": "Hôm nay"},
    {"id": "L1-28", "level": 1, "japanese": "明日", "reading": "あした", "vietnamese": "Ngày mai"},
    {"id": "L1-29", "level": 1, "japanese": "昨日", "reading": "きのう", "vietnamese": "Hôm qua"},
    {"id": "L1-30", "level": 1, "japanese": "時間", "reading": "じかん", "vietnamese": "Thời gian"},
    {"id": "L1-31", "level": 1, "japanese": "電話", "reading": "でんわ", "vietnamese": "Điện thoại"},
    {"id": "L1-32", "level": 1, "japanese": "新聞", "reading": "しんぶん", "vietnamese": "Báo"},
    {"id": "L1-33", "level": 1, "japanese": "お金", "reading": "おかね", "vietnamese": "Tiền"},
    {"id": "L1-34", "level": 1, "japanese": "服", "reading": "ふく", "vietnamese": "Quần áo"},
    {"id": "L1-35", "level": 1, "japanese": "靴", "reading": "くつ", "vietnamese": "Giày"},
    {"id": "L1-36", "level": 1, "japanese": "帽子", "reading": "ぼうし", "vietnamese": "Mũ"},
    {"id": "L1-37", "level": 1, "japanese": "机", "reading": "つくえ", "vietnamese": "Bàn (học/làm việc)"},
    {"id": "L1-38", "level": 1, "japanese": "椅子", "reading": "いす", "vietnamese": "Ghế"},
    {"id": "L1-39", "level": 1, "japanese": "部屋", "reading": "へや", "vietnamese": "Phòng"},
    {"id": "L1-40", "level": 1, "japanese": "牛乳", "reading": "ぎゅうにゅう", "vietnamese": "Sữa bò"},

    # ---------------- Level 2: 日常会話 ----------------
    {"id": "L2-01", "level": 2, "japanese": "おはようございます", "reading": "おはようございます", "vietnamese": "Chào buổi sáng"},
    {"id": "L2-02", "level": 2, "japanese": "ありがとうございます", "reading": "ありがとうございます", "vietnamese": "Cảm ơn"},
    {"id": "L2-03", "level": 2, "japanese": "すみません", "reading": "すみません", "vietnamese": "Xin lỗi / Xin phép"},
    {"id": "L2-04", "level": 2, "japanese": "お元気ですか", "reading": "おげんきですか", "vietnamese": "Bạn khỏe không?"},
    {"id": "L2-05", "level": 2, "japanese": "いただきます", "reading": "いただきます", "vietnamese": "Mời (trước khi ăn)"},
    {"id": "L2-06", "level": 2, "japanese": "ごちそうさまでした", "reading": "ごちそうさまでした", "vietnamese": "Cảm ơn vì bữa ăn"},
    {"id": "L2-07", "level": 2, "japanese": "お願いします", "reading": "おねがいします", "vietnamese": "Xin nhờ / Làm ơn"},
    {"id": "L2-08", "level": 2, "japanese": "いくらですか", "reading": "いくらですか", "vietnamese": "Bao nhiêu tiền?"},
    {"id": "L2-09", "level": 2, "japanese": "どこですか", "reading": "どこですか", "vietnamese": "Ở đâu?"},
    {"id": "L2-10", "level": 2, "japanese": "わかりました", "reading": "わかりました", "vietnamese": "Tôi hiểu rồi"},
    {"id": "L2-11", "level": 2, "japanese": "はじめまして", "reading": "はじめまして", "vietnamese": "Rất vui được gặp bạn"},
    {"id": "L2-12", "level": 2, "japanese": "よろしくお願いします", "reading": "よろしくおねがいします", "vietnamese": "Mong được giúp đỡ"},
    {"id": "L2-13", "level": 2, "japanese": "さようなら", "reading": "さようなら", "vietnamese": "Tạm biệt"},
    {"id": "L2-14", "level": 2, "japanese": "また明日", "reading": "またあした", "vietnamese": "Hẹn gặp lại ngày mai"},
    {"id": "L2-15", "level": 2, "japanese": "お休みなさい", "reading": "おやすみなさい", "vietnamese": "Chúc ngủ ngon"},
    {"id": "L2-16", "level": 2, "japanese": "いってきます", "reading": "いってきます", "vietnamese": "Con đi đây"},
    {"id": "L2-17", "level": 2, "japanese": "ただいま", "reading": "ただいま", "vietnamese": "Con về rồi"},
    {"id": "L2-18", "level": 2, "japanese": "おかえりなさい", "reading": "おかえりなさい", "vietnamese": "Chào mừng về nhà"},
    {"id": "L2-19", "level": 2, "japanese": "大丈夫です", "reading": "だいじょうぶです", "vietnamese": "Không sao"},
    {"id": "L2-20", "level": 2, "japanese": "おめでとうございます", "reading": "おめでとうございます", "vietnamese": "Xin chúc mừng"},
    {"id": "L2-21", "level": 2, "japanese": "お大事に", "reading": "おだいじに", "vietnamese": "Mong bạn mau khỏe"},
    {"id": "L2-22", "level": 2, "japanese": "頑張ってください", "reading": "がんばってください", "vietnamese": "Cố lên nhé"},
    {"id": "L2-23", "level": 2, "japanese": "お疲れ様でした", "reading": "おつかれさまでした", "vietnamese": "Bạn đã vất vả rồi"},
    {"id": "L2-24", "level": 2, "japanese": "いいえ、違います", "reading": "いいえ、ちがいます", "vietnamese": "Không, không phải vậy"},
    {"id": "L2-25", "level": 2, "japanese": "ちょっと待ってください", "reading": "ちょっとまってください", "vietnamese": "Xin đợi một chút"},
    {"id": "L2-26", "level": 2, "japanese": "気をつけてください", "reading": "きをつけてください", "vietnamese": "Hãy cẩn thận nhé"},
    {"id": "L2-27", "level": 2, "japanese": "トイレはどこですか", "reading": "といれはどこですか", "vietnamese": "Nhà vệ sinh ở đâu?"},
    {"id": "L2-28", "level": 2, "japanese": "何時ですか", "reading": "なんじですか", "vietnamese": "Mấy giờ rồi?"},
    {"id": "L2-29", "level": 2, "japanese": "元気です", "reading": "げんきです", "vietnamese": "Tôi khỏe"},
    {"id": "L2-30", "level": 2, "japanese": "どういたしまして", "reading": "どういたしまして", "vietnamese": "Không có gì"},

    # ---------------- Level 3: 学校生活 ----------------
    {"id": "L3-01", "level": 3, "japanese": "授業", "reading": "じゅぎょう", "vietnamese": "Tiết học"},
    {"id": "L3-02", "level": 3, "japanese": "宿題", "reading": "しゅくだい", "vietnamese": "Bài tập về nhà"},
    {"id": "L3-03", "level": 3, "japanese": "試験", "reading": "しけん", "vietnamese": "Kỳ thi"},
    {"id": "L3-04", "level": 3, "japanese": "教科書", "reading": "きょうかしょ", "vietnamese": "Sách giáo khoa"},
    {"id": "L3-05", "level": 3, "japanese": "部活", "reading": "ぶかつ", "vietnamese": "Hoạt động câu lạc bộ"},
    {"id": "L3-06", "level": 3, "japanese": "出席", "reading": "しゅっせき", "vietnamese": "Có mặt / điểm danh"},
    {"id": "L3-07", "level": 3, "japanese": "遅刻", "reading": "ちこく", "vietnamese": "Đi trễ"},
    {"id": "L3-08", "level": 3, "japanese": "休み時間", "reading": "やすみじかん", "vietnamese": "Giờ nghỉ giải lao"},
    {"id": "L3-09", "level": 3, "japanese": "クラスメート", "reading": "くらすめーと", "vietnamese": "Bạn cùng lớp"},
    {"id": "L3-10", "level": 3, "japanese": "卒業", "reading": "そつぎょう", "vietnamese": "Tốt nghiệp"},
    {"id": "L3-11", "level": 3, "japanese": "黒板", "reading": "こくばん", "vietnamese": "Bảng đen"},
    {"id": "L3-12", "level": 3, "japanese": "教室", "reading": "きょうしつ", "vietnamese": "Phòng học"},
    {"id": "L3-13", "level": 3, "japanese": "図書館", "reading": "としょかん", "vietnamese": "Thư viện"},
    {"id": "L3-14", "level": 3, "japanese": "体育館", "reading": "たいいくかん", "vietnamese": "Nhà thể dục"},
    {"id": "L3-15", "level": 3, "japanese": "運動会", "reading": "うんどうかい", "vietnamese": "Hội thao"},
    {"id": "L3-16", "level": 3, "japanese": "文化祭", "reading": "ぶんかさい", "vietnamese": "Lễ hội văn hóa"},
    {"id": "L3-17", "level": 3, "japanese": "成績", "reading": "せいせき", "vietnamese": "Thành tích học tập"},
    {"id": "L3-18", "level": 3, "japanese": "提出する", "reading": "ていしゅつする", "vietnamese": "Nộp (bài tập)"},
    {"id": "L3-19", "level": 3, "japanese": "先輩", "reading": "せんぱい", "vietnamese": "Đàn anh/chị khóa trên"},
    {"id": "L3-20", "level": 3, "japanese": "後輩", "reading": "こうはい", "vietnamese": "Đàn em khóa dưới"},
    {"id": "L3-21", "level": 3, "japanese": "担任の先生", "reading": "たんにんのせんせい", "vietnamese": "Giáo viên chủ nhiệm"},
    {"id": "L3-22", "level": 3, "japanese": "入学", "reading": "にゅうがく", "vietnamese": "Nhập học"},
    {"id": "L3-23", "level": 3, "japanese": "時間割", "reading": "じかんわり", "vietnamese": "Thời khóa biểu"},
    {"id": "L3-24", "level": 3, "japanese": "校長先生", "reading": "こうちょうせんせい", "vietnamese": "Hiệu trưởng"},
    {"id": "L3-25", "level": 3, "japanese": "保健室", "reading": "ほけんしつ", "vietnamese": "Phòng y tế"},

    # ---------------- Level 4: 日本での生活 ----------------
    {"id": "L4-01", "level": 4, "japanese": "役所", "reading": "やくしょ", "vietnamese": "Cơ quan hành chính"},
    {"id": "L4-02", "level": 4, "japanese": "保険証", "reading": "ほけんしょう", "vietnamese": "Thẻ bảo hiểm"},
    {"id": "L4-03", "level": 4, "japanese": "在留カード", "reading": "ざいりゅうかーど", "vietnamese": "Thẻ cư trú"},
    {"id": "L4-04", "level": 4, "japanese": "アルバイト", "reading": "あるばいと", "vietnamese": "Làm thêm"},
    {"id": "L4-05", "level": 4, "japanese": "家賃", "reading": "やちん", "vietnamese": "Tiền thuê nhà"},
    {"id": "L4-06", "level": 4, "japanese": "引っ越し", "reading": "ひっこし", "vietnamese": "Chuyển nhà"},
    {"id": "L4-07", "level": 4, "japanese": "ゴミの分別", "reading": "ごみのぶんべつ", "vietnamese": "Phân loại rác"},
    {"id": "L4-08", "level": 4, "japanese": "病院", "reading": "びょういん", "vietnamese": "Bệnh viện"},
    {"id": "L4-09", "level": 4, "japanese": "銀行口座", "reading": "ぎんこうこうざ", "vietnamese": "Tài khoản ngân hàng"},
    {"id": "L4-10", "level": 4, "japanese": "契約", "reading": "けいやく", "vietnamese": "Hợp đồng"},
    {"id": "L4-11", "level": 4, "japanese": "市役所", "reading": "しやくしょ", "vietnamese": "Ủy ban thành phố"},
    {"id": "L4-12", "level": 4, "japanese": "住民票", "reading": "じゅうみんひょう", "vietnamese": "Giấy chứng nhận cư trú"},
    {"id": "L4-13", "level": 4, "japanese": "携帯電話", "reading": "けいたいでんわ", "vietnamese": "Điện thoại di động"},
    {"id": "L4-14", "level": 4, "japanese": "電気代", "reading": "でんきだい", "vietnamese": "Tiền điện"},
    {"id": "L4-15", "level": 4, "japanese": "水道代", "reading": "すいどうだい", "vietnamese": "Tiền nước"},
    {"id": "L4-16", "level": 4, "japanese": "ガス代", "reading": "がすだい", "vietnamese": "Tiền ga"},
    {"id": "L4-17", "level": 4, "japanese": "郵便局", "reading": "ゆうびんきょく", "vietnamese": "Bưu điện"},
    {"id": "L4-18", "level": 4, "japanese": "コンビニ", "reading": "こんびに", "vietnamese": "Cửa hàng tiện lợi"},
    {"id": "L4-19", "level": 4, "japanese": "スーパー", "reading": "すーぱー", "vietnamese": "Siêu thị"},
    {"id": "L4-20", "level": 4, "japanese": "薬局", "reading": "やっきょく", "vietnamese": "Hiệu thuốc"},
    {"id": "L4-21", "level": 4, "japanese": "交番", "reading": "こうばん", "vietnamese": "Trạm cảnh sát khu vực"},
    {"id": "L4-22", "level": 4, "japanese": "定期券", "reading": "ていきけん", "vietnamese": "Vé tháng tàu điện"},
    {"id": "L4-23", "level": 4, "japanese": "健康診断", "reading": "けんこうしんだん", "vietnamese": "Khám sức khỏe định kỳ"},
    {"id": "L4-24", "level": 4, "japanese": "税金", "reading": "ぜいきん", "vietnamese": "Thuế"},
    {"id": "L4-25", "level": 4, "japanese": "台風", "reading": "たいふう", "vietnamese": "Bão"},

    # ---------------- Level 5: 上級表現 ----------------
    {"id": "L5-01", "level": 5, "japanese": "手続き", "reading": "てつづき", "vietnamese": "Thủ tục"},
    {"id": "L5-02", "level": 5, "japanese": "申請する", "reading": "しんせいする", "vietnamese": "Nộp đơn / đăng ký"},
    {"id": "L5-03", "level": 5, "japanese": "承知いたしました", "reading": "しょうちいたしました", "vietnamese": "Tôi đã hiểu rõ (kính ngữ)"},
    {"id": "L5-04", "level": 5, "japanese": "お手数をおかけします", "reading": "おてすうをおかけします", "vietnamese": "Xin lỗi vì đã làm phiền"},
    {"id": "L5-05", "level": 5, "japanese": "恐れ入りますが", "reading": "おそれいりますが", "vietnamese": "Xin lỗi nhưng (lịch sự)"},
    {"id": "L5-06", "level": 5, "japanese": "大変申し訳ございません", "reading": "たいへんもうしわけございません", "vietnamese": "Tôi thành thật xin lỗi"},
    {"id": "L5-07", "level": 5, "japanese": "ご検討ください", "reading": "ごけんとうください", "vietnamese": "Xin vui lòng cân nhắc"},
    {"id": "L5-08", "level": 5, "japanese": "差し支えなければ", "reading": "さしつかえなければ", "vietnamese": "Nếu không phiền"},
    {"id": "L5-09", "level": 5, "japanese": "拝見する", "reading": "はいけんする", "vietnamese": "Xem (khiêm nhường ngữ)"},
    {"id": "L5-10", "level": 5, "japanese": "ご不明な点がございましたら", "reading": "ごふめいなてんがございましたら", "vietnamese": "Nếu có điều gì chưa rõ"},
    {"id": "L5-11", "level": 5, "japanese": "ご迷惑をおかけしました", "reading": "ごめいわくをおかけしました", "vietnamese": "Đã gây phiền phức cho quý vị, tôi xin lỗi"},
    {"id": "L5-12", "level": 5, "japanese": "よろしければ", "reading": "よろしければ", "vietnamese": "Nếu được / nếu thuận tiện"},
    {"id": "L5-13", "level": 5, "japanese": "かしこまりました", "reading": "かしこまりました", "vietnamese": "Tôi đã hiểu rõ (kính ngữ cao)"},
    {"id": "L5-14", "level": 5, "japanese": "恐縮です", "reading": "きょうしゅくです", "vietnamese": "Tôi rất ái ngại/biết ơn"},
    {"id": "L5-15", "level": 5, "japanese": "お手数ですが", "reading": "おてすうですが", "vietnamese": "Xin lỗi vì đã làm phiền quý vị"},
    {"id": "L5-16", "level": 5, "japanese": "心よりお詫び申し上げます", "reading": "こころよりおわびもうしあげます", "vietnamese": "Tôi xin thành thật xin lỗi từ đáy lòng"},
    {"id": "L5-17", "level": 5, "japanese": "何卒よろしくお願いいたします", "reading": "なにとぞよろしくおねがいいたします", "vietnamese": "Kính mong quý vị giúp đỡ"},
    {"id": "L5-18", "level": 5, "japanese": "ご遠慮なくおっしゃってください", "reading": "ごえんりょなくおっしゃってください", "vietnamese": "Xin đừng ngần ngại cho biết ý kiến"},
    {"id": "L5-19", "level": 5, "japanese": "承れません", "reading": "うけたまわれません", "vietnamese": "Rất tiếc tôi không thể tiếp nhận việc này"},
    {"id": "L5-20", "level": 5, "japanese": "お役に立てず申し訳ございません", "reading": "おやくにたてずもうしわけございません", "vietnamese": "Xin lỗi vì đã không giúp ích được gì"},
]

LEVEL_NAMES = {
    1: "レベル1: 日常単語",
    2: "レベル2: 日常会話",
    3: "レベル3: 学校生活",
    4: "レベル4: 日本での生活",
    5: "レベル5: 上級表現",
}


def get_vocab_by_level(level):
    return [v for v in VOCAB_DATA if v["level"] == level]


def get_vocab_by_id(vocab_id):
    for v in VOCAB_DATA:
        if v["id"] == vocab_id:
            return v
    return None
